### PR TITLE
Possible fix for cleaning bug #358

### PR DESCRIPTION
**Pull request by nist-anka**
Remove files git-state and version.h during make clean operation.
I added removal in ibis/CMakeLists.txt as I do not know how to do it in gitwatcher.cmake.
Simon, you might know.

### CODE REVIEW

**Comment by drouin-simon** [comment]
I think you should be able to simply move the lines to gitwatcher.cmake as this file is included in the main CMakeLists.txt so it acts like if it was in CMakeLists.txt but it is a little cleaner.

**Comment by nist-anka** [comment]
It looked to me like this would not fit the structure of  gitwatcher.cmake

**Comment by nist-anka** [comment]
I don't know where to add code to remove git_state in gitwatcher.cmake.

**Comment by nist-anka** [comment]
I still don't know how to do it

**Pull request closed without merging**
