### PR TITLE
Eliminate invalid ImageObjects from loaded scene.

### PR DESCRIPTION
**Pull request by nist-anka**

### CODE REVIEW

**Comment by drouin-simon** [comment]
I think it would make more sense to deal with this inside the object (just not set things up for rendering). There is no need to have a global mechanism.

**Comment by nist-anka** [comment]
I will do it locally.

**Comment by drouin-simon** [comment]
The scene doesn't contain any minc file for that volume? Or is it empty?

Inside ImageObject, I would verify that color table ranges are properly initialized to a value that makes sense and that image object is not empty (perhaps check the dimensions). The invalid range only results from an empty image (dimension = 0), so this is probably the only thing we have to check (i.e. is the pointer null, if not, is dimension 0). In both cases, the Setup function simply doesn't add objects to the scene.

**Comment by nist-anka** [comment]
I don't think, I can make it locally. TripleCutPlane will add image without
checking its validity and than it will crash.

**Comment by nist-anka** [comment]
Image has decent dimensions

**Comment by drouin-simon** [comment]
Is there a file on disk?

**Comment by drouin-simon** [comment]
I think this scene is valid. The problem is probably coming from volume 65.mnc, which is completely black, but has otherwise pretty regular properties, apart from lutRange, which is [nan,nan]. Normally, Ibis should be able to deal with a completely black volume. Now, the question is: what caused the lutRange to be nan? This is what we have to find out to fix the problem. I'm guessing some variable is not properly initialized somewhere.

**Comment by nist-anka** [comment]
The problem was  in creation of reconstructed volume and it was fixed since
then.
I kept the scene, I don't remember why, I should have get rid of it after
fix.
The scene loads in ibis release version.

My initial question was - should I do anything about  possibly invalid
object.
When an object is missing altogether, we issue a message. We don't check if
it can be displayed.

As for this example, I think, I should add some checking when adding image
to triple cut plane or vtkMultiImagePlane

**Comment by drouin-simon** [comment]
If you load the minc files separately and save the scene, the scene also has nan for a lutRange. We just have to figure out where the nan comes from and what other value we want to assign for this kind of volume.

**Comment by nist-anka** [comment]
OK, I'll see.
Still, we may have some other invalid files in the scenes.

**Pull request closed without merging**
