### PR TITLE
rotate camera around reference object center.

### PR DESCRIPTION
**Pull request by nist-anka**
Tested on 2 different object loaded simultaneously, and checked if changing reference works properly.

### CODE REVIEW

**Comment by hgueziri** [comment]
This is great!!
However, it only works when I change the current reference object. If I load an image, the camera will not focus on it.

**Review by hgueziri — COMMENTED** [review]
a call to `this->ReferenceTransformChanged();` here (line [492](https://github.com/IbisNeuronav/Ibis/blob/d74bd89c1ae57789b4622596b1185e3658a08930/IbisLib/view.cpp#L492) and line [499](https://github.com/IbisNeuronav/Ibis/blob/d74bd89c1ae57789b4622596b1185e3658a08930/IbisLib/view.cpp#L499)) seems to solve the problem

**Comment by nist-anka** [comment]
Maybe setting object as reference after adding to scene will solve the problem?

**Comment by hgueziri** [comment]
Works perfectly! Thanks a lot.

**Pull request merged**
