### PR TITLE
Support gcc 13+

### PR DESCRIPTION
**Pull request by raphaelchristin**
`vtk` version 9.2.5 did not support gcc 13. This was fixed in 9.2.6, so we are bumping the `vtk` version to support modern gcc versions.

### CODE REVIEW

**Comment by errollgarner** [comment]
Given, that the patch was introduced in 9.2.6 (see https://gitlab.kitware.com/vtk/vtk/-/issues/18782) and that at present time, there are compilation issues on Windows with versions greater than 9.3.0 (see https://gitlab.kitware.com/vtk/vtk/-/issues/19178), I would rather stick with 9.2.6. @raphaelchristin can you try building [https://github.com/IbisNeuronav/Ibis/tree/SupportGcc14](https://github.com/IbisNeuronav/Ibis/tree/SupportGcc14)?

**Comment by raphaelchristin** [comment]
tried to build, it did not work. Error log here, seems similar to before the patch.
[error.log](https://github.com/user-attachments/files/17333884/error.log)

**Comment by errollgarner** [comment]
Can you give a final try to https://github.com/IbisNeuronav/Ibis/tree/SupportGcc14?
It now uses your ITK changes, switches to VTK 9.3.1 and adds this [patch](https://gitlab.kitware.com/dlrdave/vtk/-/commit/bf0c21074a12f7997e2460c5fdbe8c319e0626dd) to allow VTK compilation on Windows. It works on all platforms on my side, but I can't confirm for Fedora.

**Comment by raphaelchristin** [comment]
Doing that now!

**Comment by raphaelchristin** [comment]
Build of [SupportGcc14](https://github.com/IbisNeuronav/Ibis/tree/SupportGcc14) is successful on fedora!

**Comment by errollgarner** [comment]
Merged

**Pull request closed without merging**
