### PR TITLE
buildig default hardware module flag turned off

### PR DESCRIPTION
**Pull request by nist-anka**
With this flag on SuperBuild fails. We may fix the build later.

### CODE REVIEW

**Comment by drouin-simon** [comment]
Is anybody still using the old hardware module? Should we remove it? This would be one less thing to maintain.

**Comment by hgueziri** [comment]
I agree. It is linux/mac specific and does not compile for windows anyway.

**Comment by drouin-simon** [comment]
It is only Linux in fact. Doesn't work on Mac either.

**Comment by nist-anka** [comment]
I agree, we should remove it. I'll do it
Anka

**Comment by drouin-simon** [comment]
The default HW module will simply become the IGSIO module and the code for the legacy module will be removed in a later PR.

**Pull request closed without merging**
