### PR TITLE
Transform bug296

### PR DESCRIPTION
**Pull request by nist-anka**
This change seems to correct the bug, more testing is needed.

### CODE REVIEW

**Comment by nist-anka** [comment]
I have to work more on this

**Comment by nist-anka** [comment]
If you need to cope with this problem, use this code.
I cannot come up with any other solution.  When we change the local transform of the reference object, 
View::ReferenceTransformChanged() is  called:
        vtkSmartPointer<vtkTransform> t = vtkSmartPointer<vtkTransform>::New();
        vtkCamera * cam = this->Renderer->GetActiveCamera();
        if( obj && this->Renderer )
        {
            vtkTransform * refTransform = obj->GetWorldTransform();
            t->SetInput( refTransform );
            t->Concatenate( this->PrevViewingTransform );

            cam->ApplyTransform( t );

            // backup inverted current transform
            this->PrevViewingTransform->DeepCopy( refTransform->GetMatrix() );
            this->PrevViewingTransform->Invert();

            NotifyNeedRender();
        }
ApplyTransform() modifies LocalTransform discarding concatenations.

**Comment by nist-anka** [comment]
Why the last solution is correct.
When we open an ImageObject, using ITK, we obtain a vtkImageData and we compute transformation matrix M from directional cosines. Then we set up object's local transorm  (vtkTransform) calling SetMatrix ( M). vtkTransform has 2 members that  we are using - vtkLinearTransform and Concatenation. Concatenation will list all the concatenated matrices.  Call to SetMatrix( M ) will not set matrix  directly in vtkLinearTransform member, but it will first set Concatenation to Identity and then add Pre or PostMatrixTransform in the Concatenation member of vtkTransform.  GetMatrix() will return matrix formed by concatenation of matrix from vtkLinearTransform and from Matrices in Concatenation member.
When we just set matrix elements, we are setting elements of the matrix from vtkLinearTransform member.  The Concatenation member remains unchanged and next call to GetMatrix will give you concatenated matrix.
That is why we should use SetMatrix() instead of setting matrix elements.

**Comment by hgueziri** [comment]
Still not working.
I suspect the issue to be related to the concatenation matrix as you mentioned. However, this has to do with how **vtkQtMatrixDialog** modifies the matrix. The reason is that:
- If I use the **Identity** button in the transform properties of an object, the matrix is reset via [transform->Identity();](https://github.com/IbisNeuronav/Ibis/blob/aa36272e460b738c97f79c63db59173dbc07245b/IbisLib/gui/transformeditwidget.cpp#L211) (line 211 in transformeditwidget.cpp);
- But if I open the local edit transform dialog using **Local Matrix...** button and I reset identity from the dialog window, the matrix is reset using [m_matrix->Identity();](https://github.com/IbisNeuronav/Ibis/blob/aa36272e460b738c97f79c63db59173dbc07245b/IbisVTK/vtkQt/vtkQtMatrixDialog.cpp#L193) (line 193 in vtkQtMatrixDialog.cpp).

I tried passing the transform to vtkQtMatrixDialog (instead of the matrix) and reset to identity with transform->Identity(); and it works. But still there is the problem of editing matrix elements. When editing matrix from the dialog window, the matrix elements are modified and somehow breaks the concatenation...

**Comment by nist-anka** [comment]
But that is why we have to use SetMatrix, not just change elements. I'll
look at it again, I tested today, and it seemed to work fine.
I have not checked Identity.

**Comment by nist-anka** [comment]
Still not ready

**Pull request closed without merging**
