### PR TITLE
Wrong parameter when calling Ibis CMake in superbuild.

### PR DESCRIPTION
**Pull request by drouin-simon**

### CODE REVIEW

**Comment by nist-anka** [comment]
Some details, please.

**Comment by drouin-simon** [comment]
CMakeLists.txt in the SuperBuild directory was missing -D in front of the IBIS_BUILD_DEFAULT_HARDWARE_MODULE option.

**Comment by nist-anka** [comment]
OK, I'll fix it unless you have already done it.
Thanks.
Anka

**Comment by drouin-simon** [comment]
I have fixed it, this is a pull request

**Pull request merged**
