### PR TITLE
Fixed Animate plugin for VTK OpenGL2 backend

### PR DESCRIPTION
**Pull request by drouin-simon**
This compiles on Mac but is not tested.

### CODE REVIEW

**Comment by nist-anka** [comment]
Does not compile on Ubuntu
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:115:5: error: ‘glGenFramebuffersEXT’ was not declared in this scope
     glGenFramebuffersEXT( 1, &m_fbId );
     ^~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:116:5: error: ‘glBindFramebufferEXT’ was not declared in this scope
     glBindFramebufferEXT( GL_FRAMEBUFFER_EXT, m_fbId );
     ^~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:130:5: error: ‘glFramebufferTexture2DEXT’ was not declared in this scope
     glFramebufferTexture2DEXT( GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, GL_TEXTURE_2D, m_textureId, 0 );
     ^~~~~~~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:130:5: note: suggested alternative: ‘glEGLImageTargetTexture2DOES’
     glFramebufferTexture2DEXT( GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, GL_TEXTURE_2D, m_textureId, 0 );
     ^~~~~~~~~~~~~~~~~~~~~~~~~
     glEGLImageTargetTexture2DOES
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:133:5: error: ‘glGenRenderbuffersEXT’ was not declared in this scope
     glGenRenderbuffersEXT( 1, &m_depthId );
     ^~~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:134:5: error: ‘glBindRenderbufferEXT’ was not declared in this scope
     glBindRenderbufferEXT( GL_RENDERBUFFER_EXT, m_depthId );
     ^~~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:135:5: error: ‘glRenderbufferStorageEXT’ was not declared in this scope
     glRenderbufferStorageEXT( GL_RENDERBUFFER_EXT, GL_DEPTH_COMPONENT24, m_renderSize[0], m_renderSize[1] );
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:139:5: error: ‘glFramebufferRenderbufferEXT’ was not declared in this scope
     glFramebufferRenderbufferEXT( GL_FRAMEBUFFER_EXT, GL_DEPTH_ATTACHMENT_EXT, GL_RENDERBUFFER_EXT, m_depthId );
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:142:18: error: ‘glCheckFramebufferStatusEXT’ was not declared in this scope
     GLenum ret = glCheckFramebufferStatusEXT( GL_FRAMEBUFFER_EXT );
                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp: In member function ‘void OffscreenRenderer::Cleanup()’:
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:206:5: error: ‘glBindFramebufferEXT’ was not declared in this scope
     glBindFramebufferEXT( GL_FRAMEBUFFER_EXT, 0 );
     ^~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:213:5: error: ‘glDeleteFramebuffersEXT’ was not declared in this scope
     glDeleteFramebuffersEXT( 1, &m_fbId );
     ^~~~~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:215:5: error: ‘glDeleteRenderbuffersEXT’ was not declared in this scope
     glDeleteRenderbuffersEXT( 1, &m_depthId );
     ^~~~~~~~~~~~~~~~~~~~~~~~
/home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:215:5: note: suggested alternative: ‘glDeleteTextures’
     glDeleteRenderbuffersEXT( 1, &m_depthId );
     ^~~~~~~~~~~~~~~~~~~~~~~~
     glDeleteTextures
IbisPlugins/Animate/CMakeFiles/Animate.dir/build.make:222: recipe for target 'IbisPlugins/Animate/CMakeFiles/Animate.dir/offscreenrenderer.cpp.o' failed
make[2]: *** [IbisPlugins/Animate/CMakeFiles/Animate.dir/offscreenrenderer.cpp.o] Error 1
CMakeFiles/Makefile2:869: recipe for target 'IbisPlugins/Animate/CMakeFiles/Animate.dir/all' failed
make[1]: *** [IbisPlugins/Animate/CMakeFiles/Animate.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by drouin-simon** [comment]
> Does not compile on Ubuntu
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:115:5: error: ‘glGenFramebuffersEXT’ was not declared in this scope
> glGenFramebuffersEXT( 1, &m_fbId );
> ^~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:116:5: error: ‘glBindFramebufferEXT’ was not declared in this scope
> glBindFramebufferEXT( GL_FRAMEBUFFER_EXT, m_fbId );
> ^~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:130:5: error: ‘glFramebufferTexture2DEXT’ was not declared in this scope
> glFramebufferTexture2DEXT( GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, GL_TEXTURE_2D, m_textureId, 0 );
> ^~~~~~~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:130:5: note: suggested alternative: ‘glEGLImageTargetTexture2DOES’
> glFramebufferTexture2DEXT( GL_FRAMEBUFFER_EXT, GL_COLOR_ATTACHMENT0_EXT, GL_TEXTURE_2D, m_textureId, 0 );
> ^~~~~~~~~~~~~~~~~~~~~~~~~
> glEGLImageTargetTexture2DOES
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:133:5: error: ‘glGenRenderbuffersEXT’ was not declared in this scope
> glGenRenderbuffersEXT( 1, &m_depthId );
> ^~~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:134:5: error: ‘glBindRenderbufferEXT’ was not declared in this scope
> glBindRenderbufferEXT( GL_RENDERBUFFER_EXT, m_depthId );
> ^~~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:135:5: error: ‘glRenderbufferStorageEXT’ was not declared in this scope
> glRenderbufferStorageEXT( GL_RENDERBUFFER_EXT, GL_DEPTH_COMPONENT24, m_renderSize[0], m_renderSize[1] );
> ^~~~~~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:139:5: error: ‘glFramebufferRenderbufferEXT’ was not declared in this scope
> glFramebufferRenderbufferEXT( GL_FRAMEBUFFER_EXT, GL_DEPTH_ATTACHMENT_EXT, GL_RENDERBUFFER_EXT, m_depthId );
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:142:18: error: ‘glCheckFramebufferStatusEXT’ was not declared in this scope
> GLenum ret = glCheckFramebufferStatusEXT( GL_FRAMEBUFFER_EXT );
> ^~~~~~~~~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp: In member function ‘void OffscreenRenderer::Cleanup()’:
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:206:5: error: ‘glBindFramebufferEXT’ was not declared in this scope
> glBindFramebufferEXT( GL_FRAMEBUFFER_EXT, 0 );
> ^~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:213:5: error: ‘glDeleteFramebuffersEXT’ was not declared in this scope
> glDeleteFramebuffersEXT( 1, &m_fbId );
> ^~~~~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:215:5: error: ‘glDeleteRenderbuffersEXT’ was not declared in this scope
> glDeleteRenderbuffersEXT( 1, &m_depthId );
> ^~~~~~~~~~~~~~~~~~~~~~~~
> /home/anka/ibis_work_sysQt/ibis/IbisPlugins/Animate/offscreenrenderer.cpp:215:5: note: suggested alternative: ‘glDeleteTextures’
> glDeleteRenderbuffersEXT( 1, &m_depthId );
> ^~~~~~~~~~~~~~~~~~~~~~~~
> glDeleteTextures
> IbisPlugins/Animate/CMakeFiles/Animate.dir/build.make:222: recipe for target 'IbisPlugins/Animate/CMakeFiles/Animate.dir/offscreenrenderer.cpp.o' failed
> make[2]: *** [IbisPlugins/Animate/CMakeFiles/Animate.dir/offscreenrenderer.cpp.o] Error 1
> CMakeFiles/Makefile2:869: recipe for target 'IbisPlugins/Animate/CMakeFiles/Animate.dir/all' failed
> make[1]: *** [IbisPlugins/Animate/CMakeFiles/Animate.dir/all] Error 2
> Makefile:170: recipe for target 'all' failed
> make: *** [all] Error 2

**Comment by drouin-simon** [comment]
Latest commit can help on Linux (I don't have a machine to test). Let me know if it fixes the problem. 

I think the problem came from the fact that default OpenGL on Linux is 1.1, which doesn't include functions called in offscreenrenderer.cxx, while Mac's default OpenGL is 2.0, which does include those functions. In cases where this happens, simply include "vtk_glew.h" which will define all functions and constants supported by the version that VTK wants (3.2).

**Comment by nist-anka** [comment]
Now compiles on Linux. What about Windows?

**Comment by hgueziri** [comment]
Compiles on windows. Is there a scene somewhere to test it?

**Comment by drouin-simon** [comment]
Animate can work with any kind of data. The goal is to create video sequences by animating the camera of the 3D view and exporting the result as a sequence of PNG. I haven't tested whether it is working with the updated code.

**Pull request merged**
